# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: document_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64ocument_service.proto\"<\n\rUploadRequest\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\x12\x15\n\rdocument_name\x18\x02 \x01(\t\"%\n\x0eUploadResponse\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\"\x1e\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\"Z\n\x0eSearchResponse\x12\x14\n\x0c\x64ocument_ids\x18\x01 \x03(\t\x12\x1a\n\x12\x64ocument_summaries\x18\x02 \x03(\t\x12\x16\n\x0e\x64ocument_texts\x18\x03 \x03(\t\" \n\x10SummarizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"$\n\x11SummarizeResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t2\xb0\x01\n\x0f\x44ocumentService\x12\x31\n\x0eUploadDocument\x12\x0e.UploadRequest\x1a\x0f.UploadResponse\x12\x32\n\x0fSearchDocuments\x12\x0e.SearchRequest\x1a\x0f.SearchResponse\x12\x36\n\rSummarizeText\x12\x11.SummarizeRequest\x1a\x12.SummarizeResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'document_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UPLOADREQUEST._serialized_start=26
  _UPLOADREQUEST._serialized_end=86
  _UPLOADRESPONSE._serialized_start=88
  _UPLOADRESPONSE._serialized_end=125
  _SEARCHREQUEST._serialized_start=127
  _SEARCHREQUEST._serialized_end=157
  _SEARCHRESPONSE._serialized_start=159
  _SEARCHRESPONSE._serialized_end=249
  _SUMMARIZEREQUEST._serialized_start=251
  _SUMMARIZEREQUEST._serialized_end=283
  _SUMMARIZERESPONSE._serialized_start=285
  _SUMMARIZERESPONSE._serialized_end=321
  _DOCUMENTSERVICE._serialized_start=324
  _DOCUMENTSERVICE._serialized_end=500
# @@protoc_insertion_point(module_scope)
